version: '3'
services:
  frontend:
    build:
      context: ./FE # Path to your frontend project
    ports:
      - "8080:80"
    links:
      - backend
    depends_on:
      - backend

  backend:
    build:
      context: ./BE # Path to your backend project
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: my-mongodb-container
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-db:
